;this file for FamiTone2 library generated by FamiStudio

untitled_music_data:
	.byte 1
	.word @instruments
	.word @samples-3
	.word @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4,307,256

@instruments:
	.byte $70 ;instrument 00 (Backing)
	.word @env2, @env0, @env0
	.byte $00
	.byte $30 ;instrument 01 (Bass)
	.word @env1, @env0, @env0
	.byte $00
	.byte $30 ;instrument 02 (Drum)
	.word @env1, @env0, @env0
	.byte $00
	.byte $30 ;instrument 03 (Lead)
	.word @env3, @env0, @env0
	.byte $00

@samples:
@env0:
	.byte $c0,$7f,$00,$00
@env1:
	.byte $cf,$7d,$cf,$00,$02
@env2:
	.byte $c6,$00,$00
@env3:
	.byte $c0,$c8,$ca,$c8,$c4,$c3,$c2,$c0,$00,$01

@song0ch0:
	.byte $fb, $01
@song0ch0loop:
@ref0:
	.byte $86,$32,$ed,$3a,$ed
@ref1:
	.byte $8f,$36,$ef,$30,$db
@ref2:
	.byte $f9,$e5
@ref3:
	.byte $f9,$e5
	.byte $fd
	.word @song0ch0loop

@song0ch1:
@song0ch1loop:
@ref4:
	.byte $80,$28,$b5,$2c,$b7,$2e,$eb
@ref5:
	.byte $8d,$2a,$f3,$26,$d9
@ref6:
	.byte $f9,$e5
@ref7:
	.byte $f9,$e5
	.byte $fd
	.word @song0ch1loop

@song0ch2:
@song0ch2loop:
@ref8:
	.byte $82,$1a,$ab,$00,$87,$18,$9f,$00,$8f,$18,$b9,$1c,$9f,$00,$91,$20
@ref9:
	.byte $a3,$00,$c5,$20,$ed,$1a,$81
@ref10:
	.byte $f9,$e5
@ref11:
	.byte $f9,$e5
	.byte $fd
	.word @song0ch2loop

@song0ch3:
@song0ch3loop:
@ref12:
	.byte $84,$62,$89,$00,$a9,$62,$89,$00,$a9,$62,$89,$00,$a9,$62,$89,$00,$a9
@ref13:
	.byte $62,$89,$00,$a9,$62,$89,$00,$a9,$62,$89,$00,$a9,$62,$89,$00,$a9
	.byte $ff,$10
	.word @ref13
@ref14:
	.byte $f9,$e5
	.byte $fd
	.word @song0ch3loop

@song0ch4:
@song0ch4loop:
@ref15:
	.byte $f9,$e5
@ref16:
	.byte $f9,$e5
@ref17:
	.byte $f9,$e5
@ref18:
	.byte $f9,$e5
	.byte $fd
	.word @song0ch4loop
