;this file for FamiTone2 library generated by FamiStudio

fg_arcade_music_music_data:
	.byte 4
	.word @instruments
	.word @samples-3
	.word @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4,307,256
	.word @song1ch0,@song1ch1,@song1ch2,@song1ch3,@song1ch4,307,256
	.word @song2ch0,@song2ch1,@song2ch2,@song2ch3,@song2ch4,307,256
	.word @song3ch0,@song3ch1,@song3ch2,@song3ch3,@song3ch4,307,256

@instruments:
	.byte $f0 ;instrument 00 (Harmony)
	.word @env3, @env0, @env0
	.byte $00
	.byte $b0 ;instrument 01 (Lead1)
	.word @env5, @env0, @env0
	.byte $00
	.byte $b0 ;instrument 02 (LeadOut)
	.word @env1, @env0, @env4
	.byte $00
	.byte $b0 ;instrument 03 (Main)
	.word @env3, @env0, @env0
	.byte $00
	.byte $30 ;instrument 04 (NextInningHarmony)
	.word @env2, @env0, @env0
	.byte $00

@samples:
@env0:
	.byte $c0,$7f,$00,$00
@env1:
	.byte $c5,$cd,$cf,$00,$02
@env2:
	.byte $cf,$02,$cd,$02,$cc,$02,$cb,$ca,$c9,$c8,$00,$09
@env3:
	.byte $cf,$7d,$cf,$00,$02
@env4:
	.byte $c0,$c0,$02,$be,$be,$be,$00,$01
@env5:
	.byte $cf,$08,$ce,$cd,$cc,$cc,$c8,$c6,$c0,$00,$08

@song0ch0:
	.byte $fb, $01
@song0ch0loop:
@ref0:
	.byte $f9,$f9,$f9,$c1
@ref1:
	.byte $f9,$f9,$f9,$c1
@ref2:
	.byte $f9,$f9,$f9,$c1
@ref3:
	.byte $f9,$f9,$f9,$c1
@ref4:
	.byte $f9,$f9,$f9,$c1
@ref5:
	.byte $f9,$f9,$f9,$c1
@ref6:
	.byte $f9,$f9,$f9,$c1
@ref7:
	.byte $f9,$f9,$f9,$c1
	.byte $fd
	.word @song0ch0loop

@song0ch1:
@song0ch1loop:
@ref8:
	.byte $86,$3c,$c3,$54,$a3,$4e,$a3,$4a,$9d,$44,$a3,$4a,$e9,$40,$e7,$00
@ref9:
	.byte $3c,$c9,$54,$9f,$4e,$a1,$4a,$a1,$44,$9f,$4a,$f9,$db
@ref10:
	.byte $4e,$a1,$4c,$a5,$4e,$9d,$44,$a3,$46,$9d,$4a,$a5,$4e,$c5,$46,$a1,$40,$e7
@ref11:
	.byte $83,$4e,$bd,$00,$83,$4e,$9b,$00,$83,$4e,$9f,$52,$a1,$54,$9f,$58,$a5,$52,$a7,$4e,$99,$4e,$4a,$9f,$48,$a1,$44,$9f,$44
@ref12:
	.byte $3c,$c7,$52,$a1,$4e,$9f,$4a,$9f,$44,$a1,$4a,$eb,$40,$bf,$00,$83,$40,$a1
@ref13:
	.byte $3c,$c7,$40,$9d,$44,$a1,$46,$a1,$4a,$a3,$4e,$e7,$4e,$9b,$00,$83,$4e,$a5,$52,$9d,$52
@ref14:
	.byte $54,$df,$00,$85,$54,$e7,$01,$54,$9f,$52,$a3,$4e,$a1,$4a,$a1,$48,$a1,$4a,$a1
@ref15:
	.byte $4e,$e9,$52,$e7,$54,$f9,$db,$00
	.byte $fd
	.word @song0ch1loop

@song0ch2:
@song0ch2loop:
@ref16:
	.byte $81,$80,$3a,$e9,$4a,$e9,$40,$e7,$3c,$e9
@ref17:
	.byte $81,$3a,$e9,$4a,$e9,$40,$e7,$3c,$e9
@ref18:
	.byte $81,$4a,$e7,$40,$e9,$4a,$eb,$3c,$e7
@ref19:
	.byte $83,$4a,$f9,$d7,$54,$e7,$4a,$eb
@ref20:
	.byte $3a,$eb,$4a,$e7,$40,$eb,$3c,$e7
@ref21:
	.byte $81,$3a,$e9,$40,$e7,$4a,$e9,$4a,$e9
@ref22:
	.byte $4e,$f9,$d9,$4e,$ed,$40,$e7
@ref23:
	.byte $83,$44,$e5,$48,$e9,$4a,$f9,$d7,$00,$81
	.byte $fd
	.word @song0ch2loop

@song0ch3:
@song0ch3loop:
@ref24:
	.byte $f9,$f9,$f9,$c1
@ref25:
	.byte $f9,$f9,$f9,$c1
@ref26:
	.byte $f9,$f9,$f9,$c1
@ref27:
	.byte $f9,$f9,$f9,$c1
@ref28:
	.byte $f9,$f9,$f9,$c1
@ref29:
	.byte $f9,$f9,$f9,$c1
@ref30:
	.byte $f9,$f9,$f9,$c1
@ref31:
	.byte $f9,$f9,$f9,$c1
	.byte $fd
	.word @song0ch3loop

@song0ch4:
@song0ch4loop:
@ref32:
	.byte $f9,$f9,$f9,$c1
@ref33:
	.byte $f9,$f9,$f9,$c1
@ref34:
	.byte $f9,$f9,$f9,$c1
@ref35:
	.byte $f9,$f9,$f9,$c1
@ref36:
	.byte $f9,$f9,$f9,$c1
@ref37:
	.byte $f9,$f9,$f9,$c1
@ref38:
	.byte $f9,$f9,$f9,$c1
@ref39:
	.byte $f9,$f9,$f9,$c1
	.byte $fd
	.word @song0ch4loop

@song1ch0:
	.byte $fb, $01
@ref40:
	.byte $81,$82,$32,$9d,$34,$9b,$36,$8d,$38,$9d,$3a,$8d
@ref41:
	.byte $f9,$00,$83
@song1ch0loop:
@ref42:
	.byte $f9,$85
	.byte $fd
	.word @song1ch0loop

@song1ch1:
@ref43:
	.byte $82,$4a,$9d,$4c,$9d,$4e,$8d,$50,$9d,$52,$8d
@ref44:
	.byte $f7,$00,$85
@song1ch1loop:
@ref45:
	.byte $f9,$85
	.byte $fd
	.word @song1ch1loop

@song1ch2:
@ref46:
	.byte $81,$80,$38,$99,$3a,$a1,$3c,$8b,$3e,$9f,$40,$8b
@ref47:
	.byte $9b,$00,$e1
@song1ch2loop:
@ref48:
	.byte $f9,$85
	.byte $fd
	.word @song1ch2loop

@song1ch3:
@ref49:
	.byte $f9,$85
@ref50:
	.byte $f9,$85
@song1ch3loop:
@ref51:
	.byte $f9,$85
	.byte $fd
	.word @song1ch3loop

@song1ch4:
@ref52:
	.byte $f9,$85
@ref53:
	.byte $f9,$85
@song1ch4loop:
@ref54:
	.byte $f9,$85
	.byte $fd
	.word @song1ch4loop

@song2ch0:
	.byte $fb, $01
@ref55:
	.byte $81,$84,$62,$95,$5a,$95,$56,$91,$52,$95,$00,$48,$89,$48,$89,$48,$95,$44,$95,$00,$f9,$db
@ref56:
	.byte $f9,$f9,$f9,$91
@song2ch0loop:
@ref57:
	.byte $f9,$f9,$f9,$91
	.byte $fd
	.word @song2ch0loop

@song2ch1:
@ref58:
	.byte $84,$4e,$95,$48,$97,$44,$95,$40,$93,$00,$f9,$f9,$a9
@ref59:
	.byte $f9,$f9,$f9,$91
@song2ch1loop:
@ref60:
	.byte $f9,$f9,$f9,$91
	.byte $fd
	.word @song2ch1loop

@song2ch2:
@ref61:
	.byte $f9,$f9,$f9,$91
@ref62:
	.byte $f9,$f9,$f9,$91
@song2ch2loop:
@ref63:
	.byte $f9,$f9,$f9,$91
	.byte $fd
	.word @song2ch2loop

@song2ch3:
@ref64:
	.byte $f9,$f9,$f9,$91
@ref65:
	.byte $f9,$f9,$f9,$91
@song2ch3loop:
@ref66:
	.byte $f9,$f9,$f9,$91
	.byte $fd
	.word @song2ch3loop

@song2ch4:
@ref67:
	.byte $f9,$f9,$f9,$91
@ref68:
	.byte $f9,$f9,$f9,$91
@song2ch4loop:
@ref69:
	.byte $f9,$f9,$f9,$91
	.byte $fd
	.word @song2ch4loop

@song3ch0:
	.byte $fb, $01
@song3ch0loop:
@ref70:
	.byte $84,$3c,$91,$50,$91,$4c,$91,$4a,$91,$5c,$91,$54,$8f,$58,$91,$5c,$91,$58,$d1,$00,$cb
@ref71:
	.byte $f9,$f9,$cb
	.byte $fd
	.word @song3ch0loop

@song3ch1:
@song3ch1loop:
@ref72:
	.byte $88,$44,$cd,$52,$cd,$4c,$cd,$00,$cd
@ref73:
	.byte $f9,$f9,$cb
	.byte $fd
	.word @song3ch1loop

@song3ch2:
@song3ch2loop:
@ref74:
	.byte $f9,$f9,$cb
@ref75:
	.byte $f9,$f9,$cb
	.byte $fd
	.word @song3ch2loop

@song3ch3:
@song3ch3loop:
@ref76:
	.byte $f9,$f9,$cb
@ref77:
	.byte $f9,$f9,$cb
	.byte $fd
	.word @song3ch3loop

@song3ch4:
@song3ch4loop:
@ref78:
	.byte $f9,$f9,$cb
@ref79:
	.byte $f9,$f9,$cb
	.byte $fd
	.word @song3ch4loop
