;this file for FamiTone2 library generated by FamiStudio

untitled_music_data:
	.byte 2
	.word @instruments
	.word @samples-3
	.word @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4,307,256
	.word @song1ch0,@song1ch1,@song1ch2,@song1ch3,@song1ch4,307,256

@instruments:
	.byte $30 ;instrument 00 (GameBoard)
	.word @env1, @env0, @env0
	.byte $00
	.byte $30 ;instrument 01 (Main)
	.word @env1, @env0, @env0
	.byte $00

@samples:
@env0:
	.byte $c0,$7f,$00,$00
@env1:
	.byte $cf,$7d,$cf,$00,$02

@song0ch0:
	.byte $fb, $01
@song0ch0loop:
@ref0:
	.byte $f9,$f9,$f9,$c1
@ref1:
	.byte $f9,$f9,$f9,$c1
@ref2:
	.byte $f9,$f9,$f9,$c1
@ref3:
	.byte $f9,$f9,$f9,$c1
@ref4:
	.byte $f9,$f9,$f9,$c1
@ref5:
	.byte $f9,$f9,$f9,$c1
@ref6:
	.byte $f9,$f9,$f9,$c1
@ref7:
	.byte $f9,$f9,$f9,$c1
@ref8:
	.byte $f9,$f9,$f9,$c1
@ref9:
	.byte $f9,$f9,$f9,$c1
@ref10:
	.byte $f9,$f9,$f9,$c1
@ref11:
	.byte $f9,$f9,$f9,$c1
@ref12:
	.byte $f9,$f9,$f9,$c1
@ref13:
	.byte $f9,$f9,$f9,$c1
@ref14:
	.byte $f9,$f9,$f9,$c1
@ref15:
	.byte $f9,$f9,$f9,$c1
	.byte $fd
	.word @song0ch0loop

@song0ch1:
@song0ch1loop:
@ref16:
	.byte $82,$3c,$c3,$54,$a3,$4e,$a3,$4a,$9d,$44,$a3,$4a,$e9,$40,$e7,$00
@ref17:
	.byte $3c,$c9,$54,$9f,$4e,$a1,$4a,$a1,$44,$9f,$4a,$f9,$db
@ref18:
	.byte $4e,$a1,$4c,$a5,$4e,$9d,$44,$a3,$46,$9d,$4a,$a5,$4e,$c5,$46,$a1,$40,$e7
@ref19:
	.byte $83,$4e,$bd,$00,$83,$4e,$9b,$00,$83,$4e,$9f,$52,$a1,$54,$9f,$58,$a5,$52,$a7,$4e,$99,$4e,$4a,$9f,$48,$a1,$44,$9f,$44
@ref20:
	.byte $3c,$c7,$52,$a1,$4e,$9f,$4a,$9f,$44,$a1,$4a,$eb,$40,$bf,$00,$83,$40,$a1
@ref21:
	.byte $3c,$c7,$40,$9d,$44,$a1,$46,$a1,$4a,$a3,$4e,$e7,$4e,$9b,$00,$83,$4e,$a5,$52,$9d,$52
@ref22:
	.byte $54,$df,$00,$85,$54,$e7,$01,$54,$9f,$52,$a3,$4e,$a1,$4a,$a1,$48,$a1,$4a,$a1
@ref23:
	.byte $4e,$e9,$52,$e7,$54,$f9,$db,$00
@ref24:
	.byte $f9,$f9,$f9,$c1
@ref25:
	.byte $f9,$f9,$f9,$c1
@ref26:
	.byte $f9,$f9,$f9,$c1
@ref27:
	.byte $f9,$f9,$f9,$c1
@ref28:
	.byte $f9,$f9,$f9,$c1
@ref29:
	.byte $f9,$f9,$f9,$c1
@ref30:
	.byte $f9,$f9,$f9,$c1
@ref31:
	.byte $f9,$f9,$f9,$c1
	.byte $fd
	.word @song0ch1loop

@song0ch2:
@song0ch2loop:
@ref32:
	.byte $f9,$f9,$f9,$c1
@ref33:
	.byte $f9,$f9,$f9,$c1
@ref34:
	.byte $f9,$f9,$f9,$c1
@ref35:
	.byte $f9,$f9,$f9,$c1
@ref36:
	.byte $f9,$f9,$f9,$c1
@ref37:
	.byte $f9,$f9,$f9,$c1
@ref38:
	.byte $f9,$f9,$f9,$c1
@ref39:
	.byte $f9,$f9,$f9,$c1
@ref40:
	.byte $f9,$f9,$f9,$c1
@ref41:
	.byte $f9,$f9,$f9,$c1
@ref42:
	.byte $f9,$f9,$f9,$c1
@ref43:
	.byte $f9,$f9,$f9,$c1
@ref44:
	.byte $f9,$f9,$f9,$c1
@ref45:
	.byte $f9,$f9,$f9,$c1
@ref46:
	.byte $f9,$f9,$f9,$c1
@ref47:
	.byte $f9,$f9,$f9,$c1
	.byte $fd
	.word @song0ch2loop

@song0ch3:
@song0ch3loop:
@ref48:
	.byte $f9,$f9,$f9,$c1
@ref49:
	.byte $f9,$f9,$f9,$c1
@ref50:
	.byte $f9,$f9,$f9,$c1
@ref51:
	.byte $f9,$f9,$f9,$c1
@ref52:
	.byte $f9,$f9,$f9,$c1
@ref53:
	.byte $f9,$f9,$f9,$c1
@ref54:
	.byte $f9,$f9,$f9,$c1
@ref55:
	.byte $f9,$f9,$f9,$c1
@ref56:
	.byte $f9,$f9,$f9,$c1
@ref57:
	.byte $f9,$f9,$f9,$c1
@ref58:
	.byte $f9,$f9,$f9,$c1
@ref59:
	.byte $f9,$f9,$f9,$c1
@ref60:
	.byte $f9,$f9,$f9,$c1
@ref61:
	.byte $f9,$f9,$f9,$c1
@ref62:
	.byte $f9,$f9,$f9,$c1
@ref63:
	.byte $f9,$f9,$f9,$c1
	.byte $fd
	.word @song0ch3loop

@song0ch4:
@song0ch4loop:
@ref64:
	.byte $f9,$f9,$f9,$c1
@ref65:
	.byte $f9,$f9,$f9,$c1
@ref66:
	.byte $f9,$f9,$f9,$c1
@ref67:
	.byte $f9,$f9,$f9,$c1
@ref68:
	.byte $f9,$f9,$f9,$c1
@ref69:
	.byte $f9,$f9,$f9,$c1
@ref70:
	.byte $f9,$f9,$f9,$c1
@ref71:
	.byte $f9,$f9,$f9,$c1
@ref72:
	.byte $f9,$f9,$f9,$c1
@ref73:
	.byte $f9,$f9,$f9,$c1
@ref74:
	.byte $f9,$f9,$f9,$c1
@ref75:
	.byte $f9,$f9,$f9,$c1
@ref76:
	.byte $f9,$f9,$f9,$c1
@ref77:
	.byte $f9,$f9,$f9,$c1
@ref78:
	.byte $f9,$f9,$f9,$c1
@ref79:
	.byte $f9,$f9,$f9,$c1
	.byte $fd
	.word @song0ch4loop

@song1ch0:
	.byte $fb, $01
@song1ch0loop:
@ref80:
	.byte $f9,$f9,$cb
@ref81:
	.byte $f9,$f9,$cb
@ref82:
	.byte $f9,$f9,$cb
@ref83:
	.byte $f9,$f9,$cb
@ref84:
	.byte $f9,$f9,$cb
@ref85:
	.byte $f9,$f9,$cb
@ref86:
	.byte $f9,$f9,$cb
@ref87:
	.byte $f9,$f9,$cb
@ref88:
	.byte $f9,$f9,$cb
@ref89:
	.byte $f9,$f9,$cb
@ref90:
	.byte $f9,$f9,$cb
@ref91:
	.byte $f9,$f9,$cb
@ref92:
	.byte $f9,$f9,$cb
@ref93:
	.byte $f9,$f9,$cb
@ref94:
	.byte $f9,$f9,$cb
@ref95:
	.byte $f9,$f9,$cb
	.byte $fd
	.word @song1ch0loop

@song1ch1:
@song1ch1loop:
@ref96:
	.byte $f9,$f9,$cb
@ref97:
	.byte $f9,$f9,$cb
@ref98:
	.byte $f9,$f9,$cb
@ref99:
	.byte $f9,$f9,$cb
@ref100:
	.byte $f9,$f9,$cb
@ref101:
	.byte $f9,$f9,$cb
@ref102:
	.byte $f9,$f9,$cb
@ref103:
	.byte $f9,$f9,$cb
@ref104:
	.byte $f9,$f9,$cb
@ref105:
	.byte $f9,$f9,$cb
@ref106:
	.byte $f9,$f9,$cb
@ref107:
	.byte $f9,$f9,$cb
@ref108:
	.byte $f9,$f9,$cb
@ref109:
	.byte $f9,$f9,$cb
@ref110:
	.byte $f9,$f9,$cb
@ref111:
	.byte $f9,$f9,$cb
	.byte $fd
	.word @song1ch1loop

@song1ch2:
@song1ch2loop:
@ref112:
	.byte $80,$54,$87,$62,$87,$38,$83,$40,$83,$48,$8d,$4e,$89,$48,$91,$56,$87,$62,$87,$38,$85,$40,$f9,$d7
@ref113:
	.byte $f9,$f9,$cb
@ref114:
	.byte $f9,$f9,$cb
@ref115:
	.byte $f9,$f9,$cb
@ref116:
	.byte $f9,$f9,$cb
@ref117:
	.byte $f9,$f9,$cb
@ref118:
	.byte $f9,$f9,$cb
@ref119:
	.byte $f9,$f9,$cb
@ref120:
	.byte $f9,$f9,$cb
@ref121:
	.byte $f9,$f9,$cb
@ref122:
	.byte $f9,$f9,$cb
@ref123:
	.byte $f9,$f9,$cb
@ref124:
	.byte $f9,$f9,$cb
@ref125:
	.byte $f9,$f9,$cb
@ref126:
	.byte $f9,$f9,$cb
@ref127:
	.byte $f9,$f9,$cb
	.byte $fd
	.word @song1ch2loop

@song1ch3:
@song1ch3loop:
@ref128:
	.byte $f9,$f9,$cb
@ref129:
	.byte $f9,$f9,$cb
@ref130:
	.byte $f9,$f9,$cb
@ref131:
	.byte $f9,$f9,$cb
@ref132:
	.byte $f9,$f9,$cb
@ref133:
	.byte $f9,$f9,$cb
@ref134:
	.byte $f9,$f9,$cb
@ref135:
	.byte $f9,$f9,$cb
@ref136:
	.byte $f9,$f9,$cb
@ref137:
	.byte $f9,$f9,$cb
@ref138:
	.byte $f9,$f9,$cb
@ref139:
	.byte $f9,$f9,$cb
@ref140:
	.byte $f9,$f9,$cb
@ref141:
	.byte $f9,$f9,$cb
@ref142:
	.byte $f9,$f9,$cb
@ref143:
	.byte $f9,$f9,$cb
	.byte $fd
	.word @song1ch3loop

@song1ch4:
@song1ch4loop:
@ref144:
	.byte $f9,$f9,$cb
@ref145:
	.byte $f9,$f9,$cb
@ref146:
	.byte $f9,$f9,$cb
@ref147:
	.byte $f9,$f9,$cb
@ref148:
	.byte $f9,$f9,$cb
@ref149:
	.byte $f9,$f9,$cb
@ref150:
	.byte $f9,$f9,$cb
@ref151:
	.byte $f9,$f9,$cb
@ref152:
	.byte $f9,$f9,$cb
@ref153:
	.byte $f9,$f9,$cb
@ref154:
	.byte $f9,$f9,$cb
@ref155:
	.byte $f9,$f9,$cb
@ref156:
	.byte $f9,$f9,$cb
@ref157:
	.byte $f9,$f9,$cb
@ref158:
	.byte $f9,$f9,$cb
@ref159:
	.byte $f9,$f9,$cb
	.byte $fd
	.word @song1ch4loop
