;this file for FamiTone2 libary generated by FamiStudio

sounds:
	.word @ntsc
	.word @ntsc
@ntsc:
	.word @sfx_ntsc_base
	.word @sfx_ntsc_eatdot
	.word @sfx_ntsc_nextinning
	.word @sfx_ntsc_smash

@sfx_ntsc_base:
	.byte $86,$80,$89,$f0,$82,$01,$81,$ab,$80,$ff,$87,$d5,$88,$00,$86,$8f
	.byte $01,$80,$f6,$07,$81,$7c,$01,$87,$a9,$02,$81,$52,$03,$80,$f5,$06
	.byte $80,$f2,$87,$9f,$01,$80,$f0,$08,$87,$8e,$12,$87,$9f,$0b,$87,$8e
	.byte $09,$87,$7e,$0c,$00
@sfx_ntsc_eatdot:
	.byte $82,$00,$81,$fd,$80,$ff,$86,$80,$89,$f0,$81,$9f,$01,$81,$b3,$01
	.byte $00
@sfx_ntsc_nextinning:
	.byte $82,$00,$81,$e1,$80,$b5,$86,$80,$89,$f0,$80,$bd,$01,$80,$ff,$02
	.byte $81,$df,$01,$81,$bd,$80,$b5,$01,$80,$bd,$01,$80,$ff,$02,$81,$bb
	.byte $01,$81,$96,$80,$b5,$01,$80,$bd,$01,$80,$ff,$02,$81,$94,$03,$81
	.byte $96,$03,$81,$a9,$80,$b5,$01,$80,$bd,$01,$80,$ff,$02,$81,$a7,$01
	.byte $81,$7e,$80,$b5,$01,$80,$bd,$01,$80,$ff,$02,$81,$7c,$03,$81,$7e
	.byte $03,$81,$7c,$03,$81,$7e,$02,$00
@sfx_ntsc_smash:
	.byte $86,$80,$89,$f0,$85,$03,$84,$56,$83,$b4,$8a,$0b,$89,$fe,$01,$89
	.byte $fc,$01,$89,$fd,$01,$89,$fb,$01,$89,$fa,$01,$89,$f9,$03,$89,$f7
	.byte $03,$89,$f5,$01,$89,$f4,$01,$89,$f0,$01,$00
