;this file for FamiTone2 libary generated by nsf2data tool

sounds:
	.word @ntsc
	.word @pal
@ntsc:
	.word @sfx_ntsc_0
	.word @sfx_ntsc_1
@pal:
	.word @sfx_pal_0
	.word @sfx_pal_1

@sfx_ntsc_0:
	.byte $89,$3f,$8a,$0d,$01,$89,$3e,$01,$89,$3a,$0a,$89,$30,$12,$89,$3a
	.byte $8a,$04,$05,$8a,$01,$08,$89,$3c,$11,$00
@sfx_pal_0:
	.byte $89,$3f,$8a,$0d,$01,$89,$3e,$01,$89,$3a,$0a,$89,$30,$12,$89,$3a
	.byte $8a,$04,$05,$8a,$01,$08,$89,$3c,$1b,$00
@sfx_ntsc_1:
	.byte $83,$3f,$84,$8e,$85,$00,$06,$84,$2d,$85,$01,$07,$00
@sfx_pal_1:
	.byte $83,$3f,$84,$84,$85,$00,$06,$84,$18,$85,$01,$07,$00
