;this file for FamiTone2 library generated by FamiStudio

fg_arcade_music_music_data:
	.db 3
	.dw .instruments
	.dw .samples-3
	.dw .song0ch0,.song0ch1,.song0ch2,.song0ch3,.song0ch4,307,256
	.dw .song1ch0,.song1ch1,.song1ch2,.song1ch3,.song1ch4,307,256
	.dw .song2ch0,.song2ch1,.song2ch2,.song2ch3,.song2ch4,307,256

.instruments:
	.db $f0 ;instrument 00 (Harmony)
	.dw .env2, .env0, .env0
	.db $00
	.db $b0 ;instrument 01 (Lead1)
	.dw .env4, .env0, .env0
	.db $00
	.db $b0 ;instrument 02 (LeadOut)
	.dw .env1, .env0, .env3
	.db $00
	.db $b0 ;instrument 03 (Main)
	.dw .env2, .env0, .env0
	.db $00

.samples:
.env0:
	.db $c0,$7f,$00,$00
.env1:
	.db $c5,$cd,$cf,$00,$02
.env2:
	.db $cf,$7d,$cf,$00,$02
.env3:
	.db $c0,$c0,$02,$be,$be,$be,$00,$01
.env4:
	.db $cf,$08,$ce,$cd,$cc,$cc,$c8,$c6,$c0,$00,$08

.song0ch0:
	.db $fb, $01
.song0ch0loop:
.ref0:
	.db $f9,$f9,$f9,$c1
.ref1:
	.db $f9,$f9,$f9,$c1
.ref2:
	.db $f9,$f9,$f9,$c1
.ref3:
	.db $f9,$f9,$f9,$c1
.ref4:
	.db $f9,$f9,$f9,$c1
.ref5:
	.db $f9,$f9,$f9,$c1
.ref6:
	.db $f9,$f9,$f9,$c1
.ref7:
	.db $f9,$f9,$f9,$c1
	.db $fd
	.dw .song0ch0loop

.song0ch1:
.song0ch1loop:
.ref8:
	.db $86,$3c,$c3,$54,$a3,$4e,$a3,$4a,$9d,$44,$a3,$4a,$e9,$40,$e7,$00
.ref9:
	.db $3c,$c9,$54,$9f,$4e,$a1,$4a,$a1,$44,$9f,$4a,$f9,$db
.ref10:
	.db $4e,$a1,$4c,$a5,$4e,$9d,$44,$a3,$46,$9d,$4a,$a5,$4e,$c5,$46,$a1,$40,$e7
.ref11:
	.db $83,$4e,$bd,$00,$83,$4e,$9b,$00,$83,$4e,$9f,$52,$a1,$54,$9f,$58,$a5,$52,$a7,$4e,$99,$4e,$4a,$9f,$48,$a1,$44,$9f,$44
.ref12:
	.db $3c,$c7,$52,$a1,$4e,$9f,$4a,$9f,$44,$a1,$4a,$eb,$40,$bf,$00,$83,$40,$a1
.ref13:
	.db $3c,$c7,$40,$9d,$44,$a1,$46,$a1,$4a,$a3,$4e,$e7,$4e,$9b,$00,$83,$4e,$a5,$52,$9d,$52
.ref14:
	.db $54,$df,$00,$85,$54,$e7,$01,$54,$9f,$52,$a3,$4e,$a1,$4a,$a1,$48,$a1,$4a,$a1
.ref15:
	.db $4e,$e9,$52,$e7,$54,$f9,$db,$00
	.db $fd
	.dw .song0ch1loop

.song0ch2:
.song0ch2loop:
.ref16:
	.db $81,$80,$3a,$e9,$4a,$e9,$40,$e7,$3c,$e9
.ref17:
	.db $81,$3a,$e9,$4a,$e9,$40,$e7,$3c,$e9
.ref18:
	.db $81,$4a,$e7,$40,$e9,$4a,$eb,$3c,$e7
.ref19:
	.db $83,$4a,$f9,$d7,$54,$e7,$4a,$eb
.ref20:
	.db $3a,$eb,$4a,$e7,$40,$eb,$3c,$e7
.ref21:
	.db $81,$3a,$e9,$40,$e7,$4a,$e9,$4a,$e9
.ref22:
	.db $4e,$f9,$d9,$4e,$ed,$40,$e7
.ref23:
	.db $83,$44,$e5,$48,$e9,$4a,$f9,$d7,$00,$81
	.db $fd
	.dw .song0ch2loop

.song0ch3:
.song0ch3loop:
.ref24:
	.db $f9,$f9,$f9,$c1
.ref25:
	.db $f9,$f9,$f9,$c1
.ref26:
	.db $f9,$f9,$f9,$c1
.ref27:
	.db $f9,$f9,$f9,$c1
.ref28:
	.db $f9,$f9,$f9,$c1
.ref29:
	.db $f9,$f9,$f9,$c1
.ref30:
	.db $f9,$f9,$f9,$c1
.ref31:
	.db $f9,$f9,$f9,$c1
	.db $fd
	.dw .song0ch3loop

.song0ch4:
.song0ch4loop:
.ref32:
	.db $f9,$f9,$f9,$c1
.ref33:
	.db $f9,$f9,$f9,$c1
.ref34:
	.db $f9,$f9,$f9,$c1
.ref35:
	.db $f9,$f9,$f9,$c1
.ref36:
	.db $f9,$f9,$f9,$c1
.ref37:
	.db $f9,$f9,$f9,$c1
.ref38:
	.db $f9,$f9,$f9,$c1
.ref39:
	.db $f9,$f9,$f9,$c1
	.db $fd
	.dw .song0ch4loop

.song1ch0:
	.db $fb, $01
.ref40:
	.db $81,$82,$32,$9d,$34,$9b,$36,$8d,$38,$9d,$3a,$8d
.ref41:
	.db $f9,$00,$83
.song1ch0loop:
.ref42:
	.db $f9,$85
	.db $fd
	.dw .song1ch0loop

.song1ch1:
.ref43:
	.db $82,$4a,$9d,$4c,$9d,$4e,$8d,$50,$9d,$52,$8d
.ref44:
	.db $f7,$00,$85
.song1ch1loop:
.ref45:
	.db $f9,$85
	.db $fd
	.dw .song1ch1loop

.song1ch2:
.ref46:
	.db $81,$80,$38,$99,$3a,$a1,$3c,$8b,$3e,$9f,$40,$8b
.ref47:
	.db $9b,$00,$e1
.song1ch2loop:
.ref48:
	.db $f9,$85
	.db $fd
	.dw .song1ch2loop

.song1ch3:
.ref49:
	.db $f9,$85
.ref50:
	.db $f9,$85
.song1ch3loop:
.ref51:
	.db $f9,$85
	.db $fd
	.dw .song1ch3loop

.song1ch4:
.ref52:
	.db $f9,$85
.ref53:
	.db $f9,$85
.song1ch4loop:
.ref54:
	.db $f9,$85
	.db $fd
	.dw .song1ch4loop

.song2ch0:
	.db $fb, $01
.ref55:
	.db $81,$84,$62,$95,$5a,$95,$56,$91,$52,$95,$00,$48,$89,$48,$89,$48,$95,$44,$95,$00,$f9,$db
.ref56:
	.db $f9,$f9,$f9,$91
.song2ch0loop:
.ref57:
	.db $f9,$f9,$f9,$91
	.db $fd
	.dw .song2ch0loop

.song2ch1:
.ref58:
	.db $84,$4e,$95,$48,$97,$44,$95,$40,$93,$00,$f9,$f9,$a9
.ref59:
	.db $f9,$f9,$f9,$91
.song2ch1loop:
.ref60:
	.db $f9,$f9,$f9,$91
	.db $fd
	.dw .song2ch1loop

.song2ch2:
.ref61:
	.db $f9,$f9,$f9,$91
.ref62:
	.db $f9,$f9,$f9,$91
.song2ch2loop:
.ref63:
	.db $f9,$f9,$f9,$91
	.db $fd
	.dw .song2ch2loop

.song2ch3:
.ref64:
	.db $f9,$f9,$f9,$91
.ref65:
	.db $f9,$f9,$f9,$91
.song2ch3loop:
.ref66:
	.db $f9,$f9,$f9,$91
	.db $fd
	.dw .song2ch3loop

.song2ch4:
.ref67:
	.db $f9,$f9,$f9,$91
.ref68:
	.db $f9,$f9,$f9,$91
.song2ch4loop:
.ref69:
	.db $f9,$f9,$f9,$91
	.db $fd
	.dw .song2ch4loop
